/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.testvagrant.optimus.dashboard;

import com.testvagrant.optimus.dashboard.models.dashboard.BuildOptions;
import org.testng.annotations.Test;

import static org.testng.Assert.assertNotNull;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

}
